on: [push, workflow_dispatch]
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Configure aws credentials
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_CI_ACCESS_KEY_ID }} --secret "${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}"
      - name: Install dependencies
        run: yarn
      - name: Synth stack
        run: yarn cdk synth
      - name: Deploy stack
        run: yarn cdk deploy -c stage=test-d
